"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
 const db=window.database;if(!db)return;const u=await db.getUser();if(!u){location.href="login.html";return}
 const {data:adm}=await db.supabase.from("admins").select("role").eq("user_id",u.id).maybeSingle();if(!adm){location.href="dashboard.html";return}
 const root=document.getElementById("adminContent");document.getElementById("logout").onclick=async()=>{await db.logout();location.href="login.html"};
 document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>load(b.dataset.tab));load("dashboard");
 async function load(tab){
  root.innerHTML='<div class="c2p-card" style="padding:30px">Loading...</div>';
  if(tab==="dashboard")return dashboard();if(tab==="users")return users();if(tab==="links")return links();if(tab==="withdraws")return withdraws();if(tab==="orders")return orders();if(tab==="monetization")return monetization();if(tab==="announcements")return announcements();
 }
 async function dashboard(){const [u,w,l,o]=await Promise.all([q("users","id,balance,is_banned,created_at"),q("withdraws","id,amount,status,created_at"),q("links","id,status,type,views"),q("sell_orders","id,status,price")]);root.innerHTML=`<div class="c2p-grid">${stat("Users",u.length)}${stat("Balance",money(u.reduce((a,x)=>a+Number(x.balance||0),0)))}${stat("Links",l.length)}${stat("Pending Withdrawals",w.filter(x=>x.status==="pending").length)}${stat("Sell Orders",o.length)}${stat("Banned Users",u.filter(x=>x.is_banned).length)}</div>`}
 function stat(a,b){return `<div class="c2p-card c2p-stat"><span class="c2p-muted">${a}</span><strong>${b}</strong></div>`}
 async function users(){const rows=await q("users","id,username,email,balance,is_banned,is_premium,premium_expires_at,created_at");root.innerHTML=`<div class="c2p-card" style="padding:22px;overflow:auto"><h2>Users</h2><table style="width:100%;border-collapse:collapse"><thead><tr><th>Username</th><th>Email</th><th>Balance</th><th>Premium</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.username)}</td><td>${esc(x.email)}</td><td>${money(x.balance)}</td><td>${x.is_premium?"Active":"Free"}</td><td>${x.is_banned?"Banned":"Active"}</td><td><button class="c2p-btn user-ban" data-id="${x.id}" data-ban="${!x.is_banned}">${x.is_banned?"Unban":"Ban"}</button></td></tr>`).join("")}</tbody></table></div>`;root.querySelectorAll(".user-ban").forEach(b=>b.onclick=async()=>{const id=b.dataset.id,ban=b.dataset.ban==="true";await db.supabase.from("users").update({is_banned:ban,status:ban?"banned":"active"}).eq("id",id);if(ban)await db.supabase.from("bans").upsert({user_id:id,reason:"Admin action"});else await db.supabase.from("bans").delete().eq("user_id",id);load("users")})}
 async function links(){const rows=await q("links","id,title,short_code,type,status,views,earnings,created_at");root.innerHTML=`<div class="c2p-card" style="padding:22px;overflow:auto"><h2>Links</h2><table style="width:100%;border-collapse:collapse"><thead><tr><th>Title</th><th>Type</th><th>Views</th><th>Earnings</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.type)}</td><td>${x.views||0}</td><td>${money(x.earnings)}</td><td>${x.status}</td><td><button class="c2p-btn link-toggle" data-id="${x.id}" data-active="${x.status==="active"}">${x.status==="active"?"Disable":"Enable"}</button></td></tr>`).join("")}</tbody></table></div>`;root.querySelectorAll(".link-toggle").forEach(b=>b.onclick=async()=>{await db.supabase.from("links").update({status:b.dataset.active==="true"?"inactive":"active",updated_at:new Date().toISOString()}).eq("id",b.dataset.id);load("links")})}
 async function withdraws(){const rows=await q("withdraws","id,user_id,method,account_number,amount,fee,status,created_at");root.innerHTML=`<div class="c2p-card" style="padding:22px;overflow:auto"><h2>Withdrawals</h2><table style="width:100%"><thead><tr><th>User</th><th>Method</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.user_id}</td><td>${esc(x.method)}</td><td>${money(x.amount)}</td><td>${x.status}</td><td>${x.status==="pending"?`<button class="c2p-btn wd" data-id="${x.id}" data-status="paid">Approve</button> <button class="c2p-btn wd" data-id="${x.id}" data-status="rejected">Reject</button>`:"—"}</td></tr>`).join("")}</tbody></table></div>`;root.querySelectorAll(".wd").forEach(b=>b.onclick=async()=>{await db.supabase.from("withdraws").update({status:b.dataset.status,paid_at:b.dataset.status==="paid"?new Date().toISOString():null}).eq("id",b.dataset.id);load("withdraws")})}
 async function orders(){const rows=await q("sell_orders","id,seller_id,buyer_id,price,fee,seller_receive,status,created_at");root.innerHTML=`<div class="c2p-card" style="padding:22px;overflow:auto"><h2>Sell Orders</h2><table style="width:100%"><thead><tr><th>ID</th><th>Price</th><th>Fee</th><th>Seller Receive</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.id.slice(0,8)}…</td><td>${money(x.price)}</td><td>${money(x.fee)}</td><td>${money(x.seller_receive)}</td><td>${x.status}</td></tr>`).join("")}</tbody></table></div>`}
 async function monetization(){const rates=await q("cpm_settings","id,country,ads_cpm,sell_cpm");root.innerHTML=`<div class="c2p-card" style="padding:22px"><h2>Monetization</h2><p class="c2p-muted">CPM values are stored server-side.</p><div id="rates">${rates.map(r=>`<div style="display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px;margin:10px 0"><input value="${esc(r.country)}" data-country="${r.id}" class="rc"><input type="number" value="${r.ads_cpm}" data-id="${r.id}" class="ra"><input type="number" value="${r.sell_cpm}" data-id="${r.id}" class="rs"><button class="c2p-btn save-rate" data-id="${r.id}">Save</button></div>`).join("")}</div></div>`;root.querySelectorAll(".save-rate").forEach(b=>b.onclick=async()=>{const id=b.dataset.id;const ra=root.querySelector(`.ra[data-id="${id}"]`),rs=root.querySelector(`.rs[data-id="${id}"]`);await db.supabase.from("cpm_settings").update({ads_cpm:Number(ra.value),sell_cpm:Number(rs.value),updated_at:new Date().toISOString()}).eq("id",id);C2P.toast("CPM updated","success")})}
 async function announcements(){root.innerHTML=`<div class="c2p-card" style="padding:22px"><h2>Announcement</h2><input id="annTitle" placeholder="Title"><textarea id="annBody" placeholder="Message" style="margin-top:10px;width:100%;min-height:150px"></textarea><button id="publish" class="c2p-btn" style="margin-top:12px">Publish</button></div>`;document.getElementById("publish").onclick=async()=>{const t=annTitle.value.trim(),m=annBody.value.trim();if(!t||!m)return C2P.toast("Title and message are required","error");await db.supabase.from("announcements").insert({title:t,content:m,created_by:u.id});C2P.toast("Announcement published","success")}}
 async function q(table,select){const {data,error}=await db.supabase.from(table).select(select);if(error)throw error;return data||[]}
 function money(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0)}
 function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
});